format = "$os$username$hostname$localip$shlvl$directory$git_branch$git_commit$git_state$git_metrics$git_status$sudo$battery$time$cmd_duration$line_break$jobs$status$container$netns$shell$character"

[character]
success_symbol = '[â¯](bold green) '
error_symbol = '[âœ–](bold red) '

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 0
home_symbol = "~"
read_only = "ğŸ”’"

[os]
disabled = false

[os.symbols]
Macos = "ó°€µ "

[sudo]
disabled = false

[shell]
fish_indicator = 'ğ“•'
zsh_indicator = 'ğ“©'
bash_indicator = 'ğ“‘'
unknown_indicator = ''
style = 'cyan bold'
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true
