format = "$os$username$directory$git_branch$git_commit$git_state$git_metrics$git_status$python$sudo$cmd_duration$line_break$jobs$shell$shlvl$character"

[character]
success_symbol = '[â¯](bold green)'
error_symbol = '[âœ–](bold red)'

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 0
home_symbol = "~"
read_only = "ğŸ”’"

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[os]
disabled = false

[os.symbols]
Macos = "ó°€µ "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = 'v${major}.${minor}'
symbol = "î˜† "

[sudo]
disabled = false

[shell]
fish_indicator = 'ğ“•'
zsh_indicator = 'ğ“©'
bash_indicator = 'ğ“‘'
unknown_indicator = ''
style = 'cyan bold'
disabled = false

[shlvl]
disabled = false
format = '[$symbol]($style)'
repeat = true
symbol = 'â¯'
# Hide first 2 level of nested shell, since tmux adds one level
repeat_offset = 2
threshold = 0

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true
